distros:
  ubuntu:
    default_version: "24.04"
    supported_versions: ["22.04", "24.04", "25.10"]
    profiles: ["base", "docker", "python", "testing", "jupyter-datascience"]
  debian:
    default_version: "13"
    supported_versions: ["11", "12", "13"]
    codenames:
      "11": "bullseye"
      "12": "bookworm"
      "13": "trixie"
    profiles: ["base", "docker", "python", "testing"]
  alma:
    default_version: "10"
    supported_versions: ["8", "9", "10"]
    profiles: ["base", "docker", "python", "testing"]
  gentoo:
    default_version: "latest"
    supported_versions: ["latest"]
    profiles: ["base", "docker", "python", "testing"]
  fedora:
    default_version: "44"
    supported_versions: ["43", "44"]
    profiles: ["base", "docker", "python", "testing"]
